### ISSUE TITLE
char console support while using hypervisor-fw

### ISSUE THREAD

**Issue by praveen-pk** [cloud-hypervisor/libvirt#38]
Char Console doesn't work when hypervisor-fw is passed to guest VM.

**Comment by rbradford** [comment]
I don't understand what you're saying. Could you elaborate?

**Comment by bryteise** [comment]
When hypervisor-fw is used as the `--kernel` option to cloud-hypervisor and `--serial pty` or `--console pty` is used the device gets created successfully but the pty device doesn't appear to have input handled correctly (no input appears and there is less output than expected). This may be due to needing to update the kernel commandline of the image itself but I haven't figured this out yet.

**Comment by bryteise** [comment]
I note that this is also a problem when trying to use the custom OVMF firmware with the pty. It seems to display the same symptoms of input not being handled.

**Comment by devimc** [comment]
@praveen-pk since your bug description is quite rickety, I will try to guess what you are doing:

* You are using the ubuntu focal-server cloud image
* You are running cloud-hypervisor with `--serial pty` or `--console pty` option
* You are using `hypervisor-fw` or `OVMF.fd` as `-kernel`

If above setup is correct, then you are facing this bug https://bugs.launchpad.net/ubuntu/+source/livecd-rootfs/+bug/1870189
that can be fixed by:

* commenting out `GRUB_FORCE_PARTUUID` line in `/etc/default/grub.d/40-force-partuuid.cfg` of your focal cloud image

**or**

* updating your cloud image to [groovy](https://cloud-images.ubuntu.com/groovy/current/), since the fix has not been backported yet.

**Comment by rbradford** [comment]
Cloud Hypervisor has supported the double reboot behaviour of these images for a while. Does the pty support does not handle the the reboot correctly?

**Comment by devimc** [comment]
the pty is unusable after the reboot

**Comment by rbradford** [comment]
> the pty is unusable after the reboot

Either the framework should retry after a reboot (I guess the PTY is closed) or the PTY should be outside the VM and thus not be recreated after a reboot.

**Comment by devimc** [comment]
see https://github.com/cloud-hypervisor/cloud-hypervisor/issues/2316

**Comment by eeldy** [comment]
When I am running cloud-hypervisor with --console pty option, hypervisor-fw as -kernel and the ubuntu bionic-server-cloudimg rather than focal or groovy as disk, functionality of virsh console is OK. So I think this problem is cloud image itself. 
But if I reboot VM, pty console is unusable.

**Comment by bryteise** [comment]
Fixed via https://github.com/cloud-hypervisor/cloud-hypervisor/pull/2344
